#
# use:    JoseQuintas/hbpack/mingw_0703
# create: JoseQuintas/harbour_34/hb34_0703

name: Harbour 3.4 mingw 7.3

on:
#  push:
  schedule:
   - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.4 mingw 7.3
        x86_64-7.3.0-release-posix-sjlj-rt_v5-rev0'
        default: 'hb34_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: mingw x86_64-7.3.0-release-posix-sjlj-rt_v5-rev0
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         md c:\temp\mingw
         md c:\temp\mingw0703
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\mingw0703

    - name: Load Source Code
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         git clone https://github.com/$env:repo c:\temp\harbour34 --depth 1
         cd \temp\harbour34
#         git config user.email "you@example.com"
#         git config user.name "Your Name"
#         git pull https://github.com/vszakats/hb

    - name: Build 32 bits
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\mingw0703\mingw64\bin;c:\temp\harbour\bin
      run: |
         c:
         cd c:\temp\harbour34
         mingw32-make clean install

    - name: Build 64 bits
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw64
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\mingw0703\mingw64\bin;c:\temp\harbour\bin
      run: |
         c:
         cd \temp\harbour34
         mingw32-make clean install

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z a -r c:\temp\hb34_0703.7z c:\temp\harbour\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: hb34_0703
         path: c:\temp\hb34_0703.7z

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: mingw_0703
         path: c:\temp\mingw_0703.7z
