#
# use:    JoseQuintas/hbpack/mingw_1002
# create: JoseQuintas/harbour_34/hb34_1002
#

name: Harbour 3.4 mingw 10.2

on:
#  push:
  schedule:
   - cron: "30 1 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.4 mingw 10.2'
        default: 'hb34_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Load Mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb32_1002.yml
         workflow_conclusion: success
         name: mingw_1002_32
         path: c:\temp
         repo: JoseQuintas/harbour_32

    - name: Load Mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb32_1002.yml
         workflow_conclusion: success
         name: mingw_1002_64
         path: c:\temp
         repo: JoseQuintas/harbour_32

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         dir c:\temp
         md c:\temp\harbour
         md c:\temp\harbour\comp
         7z x -y c:\temp\mingw_1002_32.7z -oc:\temp\mingw32
         7z x -y c:\temp\mingw_1002_64.7z -oc:\temp\mingw64

    - name: Install Source Code
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         git clone https://github.com/$env:repo c:\temp\harbour34 --depth 10
         cd \temp\harbour34
         git config user.email "you@example.com"
         git config user.name "Your Name"
         git pull https://github.com/vszakats/hb

    - name: Build 32 bits
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\mingw32\bin
      run: |
         c:
         cd c:\temp\harbour34
         mingw32-make clean install

    - name: Build 64 bits
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw64
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\mingw64\bin
      run: |
         c:
         cd \temp\harbour34
         mingw32-make clean install

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp\harbour
         7z a -r c:\temp\hb34_1002.7z c:\temp\harbour\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: hb34_1002
         path: c:\temp\hb34_1002.7z

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: mingw_1002_32
         path: c:\temp\mingw_1002_32.7z

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: mingw_1002_64
         path: c:\temp\mingw_1002_64.7z
